[project]
name = "nhatvu148"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
