[project]
name = "nhatvu148"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.6.1",
    "numpy>=1.26.4",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
